openapi: '3.0.2'
info:
  title: 'Choose Your Own Adventure'
  description: 'This is the API doc for the choose your own adventure game that will be made for IT&C-410'
  version: '1.0.0' # Major, Minor, Patch
paths:
  /character:
    get:
      tags:
      - 'character'
      summary: 'Returns all the characters'
      responses:
        200:
          description: 'all of the characters'
        400:
          description: 'Invalid request'
  /character/{userID}:
    post:
      tags:
      - 'character'
      summary: 'Add a new character to a specific user'
      description: 'Add a new character to a specific user'
      parameters: 
      - name: 'userID'
        in: 'path'
        description: 'ID of user who will own this character'
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: number
                name:
                  type: string
                strength:
                  type: number
                dexterity:
                  type: number
                speech:
                  type: number
                intelligence:
                  type: number
      responses:
        201:
          description: 'Character created'
        400:
          description: 'Invalid userID'
  /user:
    get:
      tags:
      - 'user'
      summary: 'Returns all the users'
      responses:
        200:
          description: 'All of the users'
        400:
          description: 'Invalid status value'
    post:
      tags:
      - 'user'
      summary: 'Add a new user'
      description: 'Add a new user'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                currentQuestion:
                  type: number
                characterID:
                  type: number
      responses:
        201:
          description: 'User created'
        400:
          description: 'Invalid status value'
  /characters/{characterID}:
    get:
      tags:
      - 'character'
      summary: 'Returns a character by ID'
      parameters: 
      - name: 'characterID'
        in: 'path'
        description: 'ID of character to return'
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: 'All of the relevant info about the character'
        400:
          description: 'Invalid status value'
  /bag/{characterID}:
    get:
      tags:
      - 'character'
      summary: 'Returns the bag by character ID'
      parameters: 
      - name: 'characterID'
        in: 'path'
        description: 'ID of character to return'
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: 'All of the items the character has'
        400:
          description: 'Invalid status value'
  /bag/{characterID}/{itemID}:
    post:
      tags:
      - 'character'
      summary: 'Add a new item to bag'
      description: 'Add a new item into the bag given the item ID and character ID'
      parameters:
      - name: 'characterID'
        in: 'path'
        description: 'ID of character to give item'
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      - name: 'itemID'
        in: 'path'
        description: 'ID of item to give character'
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                character:
                  type: number
                item:
                  type: number
      responses:
        201:
          description: 'Item added to character bag'
        400:
          description: 'Invalid status value'
  /questions:
    get:
      tags:
      - 'question'
      summary: 'Returns all the questions'
      responses:
        200:
          description: 'all of the questions'
        400:
          description: 'Invalid status value'
    post:
      tags:
      - 'question'
      summary: 'Add a new question'
      description: 'Add a new question'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
      responses:
        201:
          description: 'Question created'
        400:
          description: 'Invalid status value'
  /answerItems:
    get:
      tags:
      - 'answer'
      summary: 'Returns all the answers and items'
      responses:
        200:
          description: 'All of the answers and items'
        400:
          description: 'Invalid status value'
    post:
      tags:
      - 'answer'
      summary: 'Add a new answer or question'
      description: 'Add a new answer or question'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
                item:
                  type: string
                question:
                  type: number
      responses:
        201:
          description: 'Answer/Item created'
        400:
          description: 'Invalid status value'
















